version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisData:/data
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root
    volumes:
      - mysqlData:/var/lib/mysql
      - ~/dump:/dump
    environment:
      - MYSQL_DATABASE=eo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  # app:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #     - nodeModules:/app/node_modules
  #     - logData:/app/log
  #   ports:
  #     - "4040:4040"
  #     - "9229:9229"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mongo
  #     - redis
  #   command: pm2 start --name "crictecScoring" --no-daemon npm -- run start
volumes:
  logData:
  mongoData:
  redisData:
  nodeModules:
  mysqlData:
